version: '3.7'
services:
  redis:
    image : redis:5.0.4
    ports:
      - "6379:6379"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - webnet
  kafka:
    image : wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - webnet
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - webnet
  gateway:
    image: ericerer/gateway
    ports:
      - "4000:4000"
    deploy:
      replicas: 1
    networks:
      - webnet
    environment:
      - FRONT_END_HOST=http://frontend:3000
      - AUTH_SERVER_HOST=http://auth-server:3002
      - BASICGRAM_HOST=http://basicgram:5000
      - WEBSOCKET_HOST=http://websocket:6000/websocket
      - USER_SERVER_HOST=http://user-server:3003
      - KAFKA_HOST=kafka
  frontend:
    image : ericerer/react
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet
  auth-server:
    image : ericerer/auth-server
    depends_on:
      - redis
      - mongodb
    ports:
      - "3002:3002"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet
    environment:
      - REDIS_HOST=redis
      - MONGO_HOST=mongodb://mongodb:27017/basicgram-database
      - GATEWAY_HOST=http://gateway:4000
  user-server:
    image : ericerer/user-server
    depends_on:
      - redis
      - mongodb
    ports:
      - "3003:3003"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet
    environment:
      - REDIS_HOST=redis
      - MONGO_HOST=mongodb://mongodb:27017/basicgram-database
      - GATEWAY_HOST=http://gateway:4000
  basicgram:
    image : ericerer/basicgram
    depends_on:
      - redis
      - mongodb
      - kafka
      - zookeeper
    ports:
      - "5000:5000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - webnet
    environment:
      - REDIS_HOST=redis
      - MONGO_HOST=mongodb://mongodb:27017/basicgram-database
      - GATEWAY_HOST=http://gateway:4000
      - KAFKA_HOST=kafka
  websocket:
    image : ericerer/websocket
    depends_on:
      - redis
      - kafka
      - zookeeper
    ports:
      - "6000:6000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - webnet
    environment:
      - REDIS_HOST=redis
      - KAFKA_HOST=kafka
networks:
  webnet: